apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: $APP_NAME
  name: $DEPLOYMENT_NAME
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: $APP_NAME
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: $APP_NAME
    spec:
      containers:
        - image: $IMAGE_NAME:$IMAGE_TAG
          name: $CONTAINER_NAME
          resources:
            requests:
              memory: "64Mi"
              cpu: "25m"
            limits:
              memory: "128Mi"
              cpu: "100m"
